### ISSUE TITLE
Enhancement - Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [COVESA/dlt-viewer#304] opened 2022-12-10 08:49 UTC
Hi.

Your source code is based on Qt.
With QT is quite easy to chnage the project from mono language GUI to multilanguage GUI.

Please consider to modify the spource code to have multilanguage GUI using external .ts/.qm language files.

Many suer will appreciate it.

Thanks.

**Comment by alexmucde** [comment] 2022-12-12 15:15
Duplicate of #296

**Closed by alexmucde** 2022-12-12 15:15 UTC
